version: '3.8'

services:
  game-server:
    build:
      context: .
      dockerfile: Dockerfile.game-server
    container_name: guess-the-jam-server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - WEBSOCKET_HOST=0.0.0.0
      - WEBSOCKET_PORT=3001
      - CORS_ORIGIN=*
    restart: unless-stopped
    networks:
      - game-network

networks:
  game-network:
    driver: bridge
